server:
  port: 7970

spring:
  application:
    name: txlcn-manager-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379

tx-lcn:
  manager:
    host: 127.0.0.1
    port: 8070