server:
  port: 11111

ribbon:
  eager-load: # 饥饿加载模式，服务启动的时候就初始化
    enabled: true
    clients: fescar-order-service,fescar-storage-service # 饥饿加载的服务名，若有多个则用逗号隔开

## Logger ##
logging:
  level:
    org.lance.cloud.fescar: debug

swagger:
  ant-paths: /caller/**