server:
  port: 11112


## Logger ##
logging:
  level:
    org.lance.cloud.api.client: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fescar?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    password: root
    username: root

swagger:
  ant-paths: /account/**